// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWY9hCuIdmHO9yPjbl-COX_lH0PuLnFF4',
    appId: '1:384221703398:web:b36a36e2d5913ec8955f27',
    messagingSenderId: '384221703398',
    projectId: 'solveathon-2210b',
    authDomain: 'solveathon-2210b.firebaseapp.com',
    storageBucket: 'solveathon-2210b.appspot.com',
    measurementId: 'G-0J9JQRGWE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDE7icxNSMRwmQ_kr9s5Aiui8uY4IRRxyY',
      appId: '1:384221703398:android:2bae18111cd20b1a955f27',
      messagingSenderId: '384221703398',
      projectId: 'solveathon-2210b',
      storageBucket: 'solveathon-2210b.appspot.com',
      databaseURL: "https://solveathon-2210b-default-rtdb.firebaseio.com");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfbIiHEysfUQ03xuH9GT5A0XT6QyFfQPE',
    appId: '1:384221703398:ios:b6fcc19d4cfee53b955f27',
    messagingSenderId: '384221703398',
    projectId: 'solveathon-2210b',
    storageBucket: 'solveathon-2210b.appspot.com',
    iosBundleId: 'com.example.solveathon',
  );
}
